### ISSUE TITLE
uwsgi does not pass http host correctly

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-www#2]
When the client sends a request using the absolute URI rather than just the path on the server, the Host header field must be ignored. However, currently only the Host header value, but not the hostname from the absolute URI will be passed on to django via uwsgi pass.

**Comment by peterthomassen** [comment]
closed via https://github.com/desec-io/desec-www/commit/df58554e3db91f90a00e717a04dae853984ae3c5
