### ISSUE TITLE
Account login

### ISSUE THREAD

**Issue by Mistero5050** [desec-io/desec-www#7]
Is it possible to log in on https://desec.io and, for example, delete your account or change password? How?

**Comment by peterthomassen** [comment]
This is currently not possible, but we are working on extending the timeline.

In the next few weeks, we are going to release our DNS API (for setting DNS records for arbitrary domains); this API currently has priority over the user management API (we receive very few requests of this type).

Until then, feel free to shoot us an email to support@desec.io if you would like to delete your account, change your email address etc.

**Comment by Mistero5050** [comment]
Ok, thank you. I will do this when I'll need it. Thanks :+1:
